import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import NavbarAndSidebar from "./compoments/NavbarAndSiderbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavbarAndSidebar />
          <div className="flex">
            {/* Content area with margin to account for sidebar */}
            <div className="ml-[256px] mt-[64px] flex-1 p-4 overflow-auto">
              <div className="min-h-full bg-white rounded-3xl">
                {children}
              </div>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
